# -*- coding: utf-8 -*-
"""AdventureWorks.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17PAb45O6EGqp39IVEzZOlnkuu68WOBj2

# <font color = cian>**Projeto 01 - Análise de Dados com Python e Pandas**
"""

#imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime

from google.colab import files
uploaded = files.upload()

df = pd.read_excel("AdventureWorks.xlsx")

"""### <font color=lightblue>**Análise Exploratória**"""

df.head()

df.shape

# Caso seja necessário saber a quantidade de registros de vários arquivos
count_array = np.array([["Adventure Works", len(df)]])
count = pd.DataFrame(count_array, columns = ['Nome do Arquivo |','Total de Registros'])
print(count)

# Total de itens por categoria
prod_cnt = df['Produto'].value_counts()

# Itens mais vendidos
fig = plt.figure(figsize= (15,5))
prod_cnt.plot(kind ='bar', color = 'maroon')
plt.xticks(rotation = 90)
plt.xlabel('Produto', fontsize = 14, fontweight = 'bold')
plt.ylabel('Quantidade', fontsize = 14, fontweight = 'bold')
plt.show()

# Top 5 Mais Vendidos
fig = plt.figure(figsize= (10,5))
prod_cnt[0:5].plot(kind ='bar', color = 'darkgoldenrod')
plt.xticks(rotation = 90)
plt.xlabel('Produto', fontsize = 14, fontweight = 'bold')
plt.ylabel('Quantidade', fontsize = 14, fontweight = 'bold')
plt.show()

"""### <font color=lightblue>**Limpeza dos Dados**"""

df.isna().sum()

"""### <font color=lightblue>**Análise Estatística Descritiva**
> 1) Qual a Quantidade de Pedidos por Usuário?
"""

df.groupby('ID Cliente')['Quantidade'].sum().sort_values(ascending = False).head()

"""> 2) Qual o Total de Produtos Vendidos?"""

df.groupby('Produto')['Quantidade'].sum().sort_values(ascending = False).head()

df.groupby("Produto")["Quantidade"].sum().sort_values(ascending=True).plot.barh(title="Total Produtos Vendidos")
plt.xlabel("Total")
plt.ylabel("Produto");

"""> 3) Qual o Valor Total Gasto por Cliente?"""

df.groupby('ID Cliente')['Valor Venda'].sum().sort_values(ascending = False).head(10)

"""> 4) Qual Valor o Cliente Gastou por Compra?"""

df.groupby([df['ID Cliente'],'Quantidade'])['Valor Venda'].sum().sort_values(ascending = False).head(10)

"""> 5) Qual o Valor Total o Cliente Gastou por Produto?"""

df.groupby([df['ID Cliente'],'ID Produto'])['Valor Venda'].sum().sort_values(ascending = False).head(10)

"""> 6) Qual a receita Total?"""

round(df['Valor Venda'].sum(), 2)

"""> 7) Qual o Custo Total por Compra?"""

df['Custo'] = df["Custo Unitário"].mul(df["Quantidade"])
df.head(1)

"""> 8) Qual o Custo Total?"""

round(df['Custo'].sum(), 2)

"""> 9) Qual o Lucro Total por Venda?"""

df['Lucro'] = df['Valor Venda'] - df['Custo']
df.head(1)

"""> 10) Qual o Lucro Total?"""

round(df['Lucro'].sum(), 2)

"""> 11) Quantos Dias até o Envio do Pedido?"""

df['Tempo_envio'] = (df['Data Envio'] - df['Data Venda']).dt.days

"""> 12) Qual a Média de Tempo  até o envio por Produto?"""

df.groupby('Produto')['Tempo_envio'].mean()

"""> 13) Qual o Lucro Total por Ano de cada Marca?"""

df.groupby([df['Data Venda'].dt.year, 'Marca'])['Lucro'].sum()

df.groupby([df['Data Venda'].dt.year, 'Marca'])['Lucro'].sum().plot.bar(title="Lucro x Marca")
plt.xlabel("Marca (p/ ANO)")
plt.ylabel("Receita")
plt.xticks(rotation = 'vertical');

df.groupby(df["Data Venda"].dt.year)["Lucro"].sum().plot.bar(title="Lucro x Ano")
plt.xlabel("Ano")
plt.ylabel("Receita");

"""> 14) Qual o Dia tem Maior Número de Pedidos?"""

# Extraindo o dia da venda
df['Dia'] = (df['Data Venda']).dt.day

# Gerando os dias de 1 a 31 e Iterando sobre a coluna para realizar a contagem
x = [i for i in range(1,32)]
y = []
for i in range(1,32):
  y.append(df[df['Dia']==i].shape[0])

#Plot
plt.figure(figsize = (10,5))
plt.bar(x,y, color = 'slateblue')
plt.xlabel('Dia do Mês', fontsize = 14, fontweight = 'bold')
plt.ylabel('Frequência', fontsize = 14, fontweight = 'bold')
plt.xticks(x)
plt.show()